---
#cloud_controller_uri: api.vcap.me
service:
  name: postgres
  version: "8.4"
  description: 'Postgres database service'
  plans: ['free']
  tags: ['postgres', 'postgres-8.4', 'relational']
host: localhost
token: "0xdeadbeef"
log_level: DEBUG
postgres_mbus: nats://localhost:4222
service_mbus: nats://localhost:4222
pid: /var/vcap/sys/run/postgres_service.pid
node_timeout: 2
