---
#cloud_controller_uri: api.vcap.me
service:
  name: postgresql
  version: "8.4"
  description: 'Postgresql database service'
  plans: ['free']
  tags: ['postgresql', 'postgresql-8.4', 'relational']
host: localhost
token: "0xdeadbeef"
log_level: DEBUG
postgres_mbus: nats://localhost:4222
service_mbus: nats://localhost:4222
pid: /var/vcap/sys/run/postgresql_service.pid
node_timeout: 2
