---
local_db: sqlite3:/var/vcap/services/postgres/postgres_node.db
base_dir: /var/vcap/services/postgres/
ip_route: 127.0.0.1
mbus: nats://localhost:4222
log_level: DEBUG
pid: /var/vcap/sys/run/postgres_node.pid
available_storage: 1024
node_id: postgres_node_1
max_db_size: 20
max_long_query: 3
postgres:
  host: localhost
  port: 5432
  user: postgres
  pass: postgres

